# Generated by Django 3.1 on 2021-02-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('Shop_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Shop',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Stock_pcs', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Vip', models.BooleanField(default=0)),
                ('Name', models.CharField(max_length=50)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('Shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.shop')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Qty', models.IntegerField(default=1)),
                ('Price', models.IntegerField()),
                ('Shop_id', models.CharField(max_length=50)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.product')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
