# Generated by Django 3.1 on 2021-02-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_schedulelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelog',
            name='To',
            field=models.TextField(),
        ),
    ]
