# Generated by Django 3.1 on 2021-02-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210223_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FuncName', models.CharField(max_length=50)),
                ('is_sent', models.BooleanField(default=0)),
                ('To', models.CharField(max_length=5000)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ScheduleLog',
            },
        ),
    ]
