# Generated by Django 3.1 on 2021-02-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210223_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Customer',
            field=models.CharField(default='Tom Cruise', max_length=50),
            preserve_default=False,
        ),
    ]
